### ISSUE TITLE
Local setup instructions seem out-of-date

### ISSUE THREAD

**Issue by StefanBlamberg** [ahmetoner/whisper-asr-webservice#61]
There seem to be a few issues with the local setup instructions
1) `pip3 install poetry==1.2.2`
The version specified here seems to have some issues with loading the dependencies (at least for me)
The latest poetry version seems to be fine, is there any reason not to use it?
2) `pip3 install torch==1.13.0+cpu -f https://download.pytorch.org/whl/torch`
There seems to be no `1.13.0+cpu` version as mentioned in https://github.com/ahmetoner/whisper-asr-webservice/issues/57
Also I was wondering why this step is required, isn't torch also part of the poetry dependencies?
3) The commited `poetry.lock` seems to be out of date
It gives a warning `Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies.`
and doesn't install all dependencies correctly and throws an error when installing `more-itertools`
Running `poetry lock` solved the problem for me
4) The 'Starting the webservice' instruction requires a global installation of `gunicorn`
I guess this should be `poetry run gunicorn --bind 0.0.0.0:9001 --workers 1 --timeout 0 app.webservice:app -k uvicorn.workers.UvicornWorker`
5) The mentioned script `poetry run whisper_asr` is no longer part of https://github.com/ahmetoner/whisper-asr-webservice/blob/main/pyproject.toml

**Comment by ahmetoner** [comment]
Hello Stefan,

Thank you for reaching out to us.

1. We were using specific poetry version because the latest version was had problem. Now, I changed it back to latest (#69).
2. Separate torch installation made for ARM and AMD based CPU images via Github actions. Now, I replaced back to toml file (#71). On the other hand, CUDA is not available on MacOS. That's why GPU image isn't working on MacOS environments.
3. Fixed in #69.
4. Fixed in #70.
5. Fixed in #70.
